service: gleamprobot-sender

provider:
  name: aws
  runtime: nodejs14.x

stage: dev
region: us-east-2
package:
  exclude:
      - node_modules/aws-sdk/**
      - gleam_sender_cron/node_modules/aws-sdk/**
      - results_sender_cron/node_modules/aws-sdk/**

functions:
  gleam_sender_cron:
    timeout: 60
    role: arn:aws:iam::067342954645:role/GleamProBot
    handler: gleam_sender_cron/main.handler
    layers:
     - arn:aws:lambda:us-east-1:067342954645:layer:teachYourSelf:5
    events:
     - schedule: rate(5 minutes)
  results_sender_cron:
    timeout: 60
    role: arn:aws:iam::067342954645:role/GleamProBot
    handler: results_sender_cron/main.handler
    layers:
     - arn:aws:lambda:us-east-1:067342954645:layer:teachYourSelf:5
    events:
     - schedule: rate(5 minutes)